### ISSUE TITLE
How do I run this app on an Android device? I am facing issues, as it works perfectly on iOS devices. I am facing issue with android device.

### ISSUE THREAD

**Issue by dyuip** [SimformSolutionsPvtLtd/SSVerticalPanoramaImage#12]
How do I run this app on an Android device? I am facing issues, as it works perfectly on iOS devices. I am facing issue with android device.

**Comment by bhargavbajani-simformsolutions** [comment]
@dyuip  
This repository is only for IOS.

**Comment by dyuip** [comment]
is it possible to run in android device???. or any other possible option
